seed: 0
num_envs: 8
total_timesteps: 2000000

ppo:
  n_steps: 2048
  batch_size: 256
  n_epochs: 5
  gamma: 0.99
  gae_lambda: 0.95
  learning_rate: 0.0001
  clip_range: 0.1
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5

log:
  log_dir: "logs"
  save_freq: 200000
  eval_freq: 100000
  eval_episodes: 50
